config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :branches do
    resources :schedules
  end
  
  get "api/branches/:branch_id/schedules", to: "api#branch_schedules"
  
  resources :users
  
  resources :turns

  get "attend", to: "attend#index"
  post "attend/:id", to: "attend#attend", as: "attend_turn"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  get "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "profile", to: "home#profile"
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :schedules, dependent: :destroy
  has_many :turns, dependent: :destroy
  
  validates :name, :address, :phone, presence: true
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  load_and_authorize_resource
  before_action :get_branch, only: [:show, :edit, :update, :destroy]

  def get_branch
    @branch = Branch.find(params[:id])
  end

  def index
    @branches = Branch.all
  end

  def show
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branch_params)
    if @branch.save
      redirect_to @branch
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @branch.update(branch_params)
      redirect_to @branch
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @branch.destroy
    redirect_to branches_url, status: :see_other
  end

  private
    def branch_params
      params.require(:branch).permit(:name, :address, :phone)
    end
end

app/views/branches/_branch.html.erb
<tr>
  <td>
    <%= branch.name %>
  </td>
  <td>
    <%= branch.address %>
  </td>
  <td>
    <%= branch.phone %>
  </td>
  <td style="text-align: right;">
    <%= link_to "Ver", branch_path(branch), class: "btn btn-secondary" %>
    <% if can? :manage, branch %>
      <%= link_to "Editar", edit_branch_path(branch), class: "btn btn-warning" %>
      <%= link_to "Borrar", branch_path(branch), class: "btn btn-danger", data: {
        turbo_method: "delete",
        turbo_confirm: "¿Estás seguro?"
      } %>
    <% end %>
  </td>
</tr>

app/views/branches/edit.html.erb
<h3>Editar sucursal</h3>

<hr>

<%= render "form", branch: @branch %>

app/views/branches/index.html.erb
<div class="row">
  <div class="col">
    <h3>Sucursales</h3>
  </div>
  <% if can? :create, Branch %>
    <div class="col" style="text-align: right;">
      <%= link_to "Nueva", new_branch_path, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

<hr>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Dirección</th>
      <th scope="col">Teléfono</th>
      <th scope="col" style="text-align: right;">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @branches %>
  </tbody>
</table>

app/views/branches/new.html.erb
<h3>Nueva sucursal</h3>

<hr>

<%= render "form" %>

app/views/branches/show.html.erb
<div class="row">
  <div class="col">
    <h3>Sucursal</h3>
  </div>
  <% if can? :manage, @branch %>
    <div class="col" style="text-align: right;">
      <%= link_to "Editar", edit_branch_path(@branch), class: "btn btn-warning" %>
      <%= link_to "Borrar", branch_path(@branch), class: "btn btn-danger", data: {
        turbo_method: "delete",
        turbo_confirm: "¿Estás seguro?"
      } %>
    </div>
  <% end %>
</div>

<hr>

<p>
  <strong>Nombre:</strong>
  <%= @branch.name %>
</p>
<p>
  <strong>Dirección:</strong>
  <%= @branch.address %>
</p>
<p>
  <strong>Teléfono:</strong>
  <%= @branch.phone %>
</p>

<br>

<div class="row">
  <div class="col">
    <h4>Horarios</h4>
  </div>
  <% if can? :create, Schedule %>
    <div class="col" style="text-align: right;">
      <%= link_to "Agregar", new_branch_schedule_path(@branch), class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

<hr>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Día</th>
      <th scope="col">Hora de apertura</th>
      <th scope="col">Hora de cierre</th>
      <% if can? :manage, @branch %>
        <th scope="col" style="text-align: right;">Acciones</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= render @branch.schedules %>
  </tbody>
</table>

<br>

<div class="text-center">
  <%= link_to "Volver", branches_path, class: "btn btn-secondary" %>
</div>