config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :branches do
    resources :schedules
  end
  
  get "api/branches/:branch_id/schedules", to: "api#branch_schedules"
  
  resources :users
  
  resources :turns

  get "attend", to: "attend#index"
  post "attend/:id", to: "attend#attend", as: "attend_turn"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  get "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "profile", to: "home#profile"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :branch
  validates :day, :start, :end, presence: true
  validate :start_is_before_end
  validate :day_is_unique

  def start_is_before_end
    if start.present? && self.end.present? && start > self.end
      errors.add(:start, "La hora de inicio debe ser anterior a la hora de fin")
    end
  end

  def day_is_unique
    if day.present? && branch.schedules.where(day: day).any?
      errors.add(:day, "Ya existe un horario para ese día")
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource
  before_action :get_branch, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :get_schedule, only: [:edit, :update, :destroy]

  def get_branch
    @branch = Branch.find(params[:branch_id])
  end

  def get_schedule
    @schedule = Schedule.find(params[:id])
  end

  def index
    redirect_to @branch
  end

  def show
    redirect_to @branch
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = @branch.schedules.create(schedule_params)
    if @schedule.save
      redirect_to @branch
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to @branch
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @schedule.destroy
    redirect_to @branch, status: :see_other
  end

  private
    def schedule_params
      params.require(:schedule).permit(:day, :start, :end)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with model: [ @branch, @schedule ] do |form| %>
  <% if @schedule.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>Se detectaron errores:</strong>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :day, class: "form-label" %>
    <%= form.select :day, options_for_select([
      "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
    ], :selected => form.object.day), {prompt: "Seleccione un día..."}, {class: "form-select"} %>
  </div>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :start, class: "form-label" %>
      <%= form.time_field :start, class: "form-control" %>
    </div>
    <div class="col">
      <%= form.label :end, class: "form-label" %>
      <%= form.time_field :end, class: "form-control" %>
    </div>
  </div>

  <div class="text-center">
    <%= form.submit class: "btn btn-danger" %>
    <%= link_to "Volver", branch_path(@branch), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<tr>
  <td>
    <%= schedule.day %>
  </td>
  <td>
    <%= schedule.start.strftime("%H:%M") %>
  </td>
  <td>
    <%= schedule.end.strftime("%H:%M") %>
  </td>
  <% if Current.user.has_role? :admin %>
    <td style="text-align: right;">
      <%= link_to "Editar", edit_branch_schedule_path(@branch, schedule), class: "btn btn-warning" %>
      <%= link_to "Borrar", branch_schedule_path(@branch, schedule), class: "btn btn-danger", data: {
        turbo_method: "delete",
        turbo_confirm: "¿Estás seguro?"
      } %>
    </td>
  <% end %>
</tr>

app/views/schedules/edit.html.erb
<h3>Editar horario para la sucursal <%= @branch.name %></h3>

<hr>

<%= render "form", branch: @branch %>

app/views/schedules/new.html.erb
<h3>Agregar horario para la sucursal <%= @branch.name %></h3>

<hr>

<%= render "form", branch: @branch %>