config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :branches do
    resources :schedules
  end
  
  get "api/branches/:branch_id/schedules", to: "api#branch_schedules"
  
  resources :users
  
  resources :turns

  get "attend", to: "attend#index"
  post "attend/:id", to: "attend#attend", as: "attend_turn"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  get "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "profile", to: "home#profile"
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :branch
  belongs_to :client, class_name: "User"
  belongs_to :manager, class_name: "User", optional: true
  validates :manager_id, presence: true, if: :attended?
  validates :result, presence: { message: "Debe ingresar un resultado" }, if: :attended?
  validates :date, :time, :reason, presence: true
  validates :date, comparison: { greater_than: Date.current, message: "La fecha debe ser posterior a la actual" }
  validate :time_is_valid?

  def time_is_valid?
    day_name = I18n.l(date, format: "%A").capitalize
    schedule = branch.schedules.find_by(day: day_name)
    if schedule.nil?
      errors.add(:time, "La sucursal no abre ese día")
    elsif time < schedule.start || time > schedule.end
      errors.add(:time, "La sucursal no abre a esa hora")
    end
  end

  def get_status_name
    case status
    when "pending"
      "Pendiente"
    when "attended"
      "Atendido"
    when "not_attended"
      "No atendido"
    end
  end

  def attended?
    status == "attended"
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  load_and_authorize_resource
  before_action :get_user, only: [:index, :create]
  before_action :get_turn, only: [:edit, :update, :destroy]

  def get_user
    @user = Current.user
  end

  def get_turn
    @turn = Turn.find(params[:id])
  end

  def index
    Turn.where(
      client_id: @user.id, status: "pending", date: Date.today - 1.day
    ).update_all(status: "not_attended")
    @pending_turns = Turn.where(client_id: @user.id, status: "pending")
    @past_turns = Turn.where(client_id: @user.id) - @pending_turns
  end

  def new
    @turn = Turn.new
  end

  def create
    params[:turn][:client_id] = @user.id
    @turn = Turn.new(turn_params)
    if @turn.save
      redirect_to turns_path, notice: "Se ha creado el turno."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @turn.update(turn_params)
      redirect_to turns_path, notice: "Se ha modificado el turno."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @turn.destroy
    redirect_to turns_path, notice: "Se ha cancelado el turno."
  end

  private
    def turn_params
      params.require(:turn).permit(:client_id, :branch_id, :date, :time, :reason)
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= form_with model: @turn do |form| %>
  <% if @turn.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>Se detectaron errores:</strong>

      <ul>
      <% @turn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label "Sucursal", class: "form-label" %>
    <%= form.select :branch_id, options_for_select(
      Branch.all.map { |branch| [branch.name, branch.id] },
      :selected => form.object.branch_id
    ), {prompt: "Seleccione una sucursal..."}, {class: "form-select", id: "turn_branch_id", onChange: "
      fetch(`/api/branches/${this.value}/schedules`)
        .then(response => response.json())
        .then(data => {
          const schedules_list = document.getElementById('branch_schedules_list');
          schedules_list.innerHTML = '';
          data.forEach(schedule => {
            const li = document.createElement('li');
            li.appendChild(document.createTextNode(
              `${schedule.day} de ${new Date(schedule.start)
                .toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' })}
              a ${new Date(schedule.end)
                .toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' })}`
            ));
            schedules_list.appendChild(li);
          });
          const schedules_block = document.getElementById('time_select');
          schedules_block.style.display = 'block';
        });
    "} %>
  </div>
  <div id="time_select" style="display: none;">
    <div class="mb-3">
      <p class="form-label">Horarios de la sucursal seleccionada:</p>
      <ul id="branch_schedules_list"></ul>
    </div>
    <div class="mb-3">
      <%= form.label :date, class: "form-label" %>
      <%= form.date_field :date, class: "form-control", min: Date.tomorrow, onChange: "
        let day = new Date(this.value).toLocaleDateString('es-AR', {
          weekday: 'long',
          timeZone: 'UTC'
        });
        day = day.charAt(0).toUpperCase() + day.slice(1);
        fetch(`/api/branches/${document.getElementById('turn_branch_id').value}/schedules`)
          .then(response => response.json())
          .then(data => {
            const schedule = data.filter(schedule => schedule.day === day)[0] || undefined;
            const time_select = document.getElementById('turn_time');
            if (schedule) {
              time_select.min = schedule.start.split('T')[1].split('-')[0];
              time_select.max = schedule.end.split('T')[1].split('-')[0];
            } else {
              time_select.min = '';
              time_select.max = '';
              time_select.value = '';
              alert('La sucursal seleccionada no abre ese día.');
            }
          });
      " %>
    </div>
    <div class="mb-3">
      <%= form.label :time, class: "form-label" %>
      <%= form.time_field :time, class: "form-control", id: "turn_time" %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label :reason, class: "form-label" %>
    <%= form.text_field :reason, class: "form-control", placeholder: "Indique el motivo..." %>
  </div>

  <div class="text-center">
    <%= form.submit class: "btn btn-danger" %>
    <%= link_to "Volver", turns_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/turns/_turn.html.erb
<% if local_assigns[:pending] %>
  <tr>
    <td>
      <%= Branch.find(turn.branch_id).name %>
    </td>
    <td>
      <%= turn.date.strftime("%d/%m/%Y") %>
    </td>
    <td>
      <%= turn.time.strftime("%H:%M") %>
    </td>
    <td>
      <%= turn.reason %>
    </td>
    <td>
      <%= turn.get_status_name %>
    </td>
    <td style="text-align: right;">
      <%= link_to "Modificar", edit_turn_path(turn), class: "btn btn-warning" %>
      <%= link_to "Cancelar", turn_path(turn), class: "btn btn-danger", data: {
        turbo_method: "delete",
        turbo_confirm: "¿Estás seguro?"
      } %>
    </td>
  </tr>
<% else %>
  <tr>
    <td>
      <%= Branch.find(turn.branch_id).name %>
    </td>
    <td>
      <%= turn.date.strftime("%d/%m/%Y") %>
    </td>
    <td>
      <%= turn.time.strftime("%H:%M") %>
    </td>
    <td>
      <%= turn.reason %>
    </td>
    <td>
      <%= turn.get_status_name %>
    </td>
    <td>
      <%= turn.manager_id ? User.find(turn.manager_id).name : "" %>
    </td>
    <td style="text-align: right;">
      <%= turn.result %>
    </td>
  </tr>
<% end %>

app/views/turns/edit.html.erb
<h3>Modificar turno</h3>

<hr>

<%= render "form", client: @client %>

app/views/turns/index.html.erb
<div class="row">
  <div class="col">
    <h3>Mis turnos</h3>
  </div>
  <div class="col" style="text-align: right;">
    <%= link_to "Solicitar turno", new_turn_path, class: "btn btn-danger" %>
  </div>
</div>

<hr>

<h4>Turnos pendientes</h4>
<% if @pending_turns.empty? %>
  <p class="alert alert-warning">No hay turnos pendientes.</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Sucursal</th>
        <th scope="col">Fecha</th>
        <th scope="col">Hora</th>
        <th scope="col">Motivo</th>
        <th scope="col">Estado</th>
        <th scope="col" style="text-align: right;">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <%= render @pending_turns, pending: true %>
    </tbody>
  </table>
<% end %>

<hr>

<h4>Turnos pasados</h4>
<% if @past_turns.empty? %>
  <p class="alert alert-warning">No hay turnos pasados.</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Sucursal</th>
        <th scope="col">Fecha</th>
        <th scope="col">Hora</th>
        <th scope="col">Motivo</th>
        <th scope="col">Estado</th>
        <th scope="col">Responsable</th>
        <th scope="col" style="text-align: right;">Resultado</th>
      </tr>
    </thead>
    <tbody>
      <%= render @past_turns, pending: false %>
    </tbody>
  </table>
<% end %>

app/views/turns/new.html.erb
<h3>Solicitar turno</h3>

<hr>

<%= render "form" %>