config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :branches do
    resources :schedules
  end
  
  get "api/branches/:branch_id/schedules", to: "api#branch_schedules"
  
  resources :users
  
  resources :turns

  get "attend", to: "attend#index"
  post "attend/:id", to: "attend#attend", as: "attend_turn"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  get "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "profile", to: "home#profile"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banco Ruby</title>
    <meta name="description" content="Sistema web para gestión de turnos bancarios.">
    <meta name="author" content="Gregorio Maclen">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid" style="padding-left: 3%; padding-right: 3%;">
        <a class="navbar-brand" href=<%= root_path %>>
          <img src="/favicon.ico" width="30" height="30" class="d-inline-block align-text-top" style="margin-right: 5%;">
          Banco Ruby
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-nav ms-auto">
            <ul class="navbar-nav navbar-right me-auto mb-2 mb-lg-0">
              <% if Current.user %>
                <% if Current.user.has_role? :client %>
                  <li class="nav-item">
                    <a class="nav-link" href=<%= turns_path %>>Mis turnos</a>
                  </li>
                <% else %>
                  <% if Current.user.has_role? :manager %>
                    <li class="nav-item">
                      <a class="nav-link" href=<%= attend_path %>>Atender</a>
                    </li>
                  <% end %>
                  <li class="nav-item dropdown">                                
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Gestionar
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href=<%= branches_path %>>Sucursales</a></li>
                      <li><a class="dropdown-item" href=<%= users_path %>>Usuarios</a></li>
                    </ul>
                  </li>
                <% end %>
                <li class="nav-item dropdown">                                
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= Current.user.name %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href=<%= profile_path %>>Mi perfil</a></li>
                    <li><a class="dropdown-item" href=<%= logout_path %>>Cerrar sesión</a></li>
                  </ul>
                </li>
              <% else %>
                <li class="nav-item">
                  <a class="nav-link" href=<%= sign_in_path %>>Acceder</a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="container-sm" id="content">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div id="footer">
      Gregorio Maclen - TTPS Ruby 2022
    </div>
  </body>
</html>